/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FilterGroup, RecipeCardData, TagTone } from "./types";
export { FilterGroup, RecipeCardData, TagTone } from "./types";
export namespace Components {
    interface RfEmptyState {
        /**
          * @default 'Nothing here yet'
         */
        "heading": string;
        /**
          * @default '🍲'
         */
        "icon": string;
        /**
          * @default ''
         */
        "message": string;
    }
    interface RfFilterBar {
        /**
          * @default []
         */
        "groups": FilterGroup[];
        /**
          * @default true
         */
        "resettable": boolean;
        /**
          * @default {}
         */
        "selected": Record<string, string>;
    }
    interface RfModal {
        /**
          * @default true
         */
        "dismissible": boolean;
        /**
          * @default ''
         */
        "heading": string;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
    }
    interface RfRating {
        /**
          * @default 'Rating'
         */
        "label": string;
        /**
          * @default 5
         */
        "max": number;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default 0
         */
        "value": number;
    }
    interface RfRecipeCard {
        /**
          * @default ''
         */
        "badge": string;
        /**
          * @default false
         */
        "compact": boolean;
        /**
          * @default false
         */
        "favorite": boolean;
        "recipe": RecipeCardData;
    }
    interface RfSearchBar {
        /**
          * @default 350
         */
        "debounce": number;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default 'Search recipes'
         */
        "placeholder": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface RfTag {
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default false
         */
        "removable": boolean;
        /**
          * @default 'neutral'
         */
        "tone": TagTone;
    }
}
export interface RfFilterBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfFilterBarElement;
}
export interface RfModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfModalElement;
}
export interface RfRatingCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfRatingElement;
}
export interface RfRecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfRecipeCardElement;
}
export interface RfSearchBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfSearchBarElement;
}
export interface RfTagCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfTagElement;
}
declare global {
    interface HTMLRfEmptyStateElement extends Components.RfEmptyState, HTMLStencilElement {
    }
    var HTMLRfEmptyStateElement: {
        prototype: HTMLRfEmptyStateElement;
        new (): HTMLRfEmptyStateElement;
    };
    interface HTMLRfFilterBarElementEventMap {
        "rfFilterChange": { group: string; value: string };
        "rfFilterReset": void;
    }
    interface HTMLRfFilterBarElement extends Components.RfFilterBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfFilterBarElementEventMap>(type: K, listener: (this: HTMLRfFilterBarElement, ev: RfFilterBarCustomEvent<HTMLRfFilterBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfFilterBarElementEventMap>(type: K, listener: (this: HTMLRfFilterBarElement, ev: RfFilterBarCustomEvent<HTMLRfFilterBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfFilterBarElement: {
        prototype: HTMLRfFilterBarElement;
        new (): HTMLRfFilterBarElement;
    };
    interface HTMLRfModalElementEventMap {
        "rfClose": void;
    }
    interface HTMLRfModalElement extends Components.RfModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfModalElementEventMap>(type: K, listener: (this: HTMLRfModalElement, ev: RfModalCustomEvent<HTMLRfModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfModalElementEventMap>(type: K, listener: (this: HTMLRfModalElement, ev: RfModalCustomEvent<HTMLRfModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfModalElement: {
        prototype: HTMLRfModalElement;
        new (): HTMLRfModalElement;
    };
    interface HTMLRfRatingElementEventMap {
        "rfRate": number;
    }
    interface HTMLRfRatingElement extends Components.RfRating, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfRatingElementEventMap>(type: K, listener: (this: HTMLRfRatingElement, ev: RfRatingCustomEvent<HTMLRfRatingElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfRatingElementEventMap>(type: K, listener: (this: HTMLRfRatingElement, ev: RfRatingCustomEvent<HTMLRfRatingElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfRatingElement: {
        prototype: HTMLRfRatingElement;
        new (): HTMLRfRatingElement;
    };
    interface HTMLRfRecipeCardElementEventMap {
        "rfSelect": RecipeCardData;
        "rfFavoriteToggle": { recipe: RecipeCardData; favorite: boolean };
    }
    interface HTMLRfRecipeCardElement extends Components.RfRecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfRecipeCardElementEventMap>(type: K, listener: (this: HTMLRfRecipeCardElement, ev: RfRecipeCardCustomEvent<HTMLRfRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfRecipeCardElementEventMap>(type: K, listener: (this: HTMLRfRecipeCardElement, ev: RfRecipeCardCustomEvent<HTMLRfRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfRecipeCardElement: {
        prototype: HTMLRfRecipeCardElement;
        new (): HTMLRfRecipeCardElement;
    };
    interface HTMLRfSearchBarElementEventMap {
        "rfSearch": string;
        "rfClear": void;
    }
    interface HTMLRfSearchBarElement extends Components.RfSearchBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfSearchBarElementEventMap>(type: K, listener: (this: HTMLRfSearchBarElement, ev: RfSearchBarCustomEvent<HTMLRfSearchBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfSearchBarElementEventMap>(type: K, listener: (this: HTMLRfSearchBarElement, ev: RfSearchBarCustomEvent<HTMLRfSearchBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfSearchBarElement: {
        prototype: HTMLRfSearchBarElement;
        new (): HTMLRfSearchBarElement;
    };
    interface HTMLRfTagElementEventMap {
        "rfRemove": string;
    }
    interface HTMLRfTagElement extends Components.RfTag, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfTagElementEventMap>(type: K, listener: (this: HTMLRfTagElement, ev: RfTagCustomEvent<HTMLRfTagElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfTagElementEventMap>(type: K, listener: (this: HTMLRfTagElement, ev: RfTagCustomEvent<HTMLRfTagElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfTagElement: {
        prototype: HTMLRfTagElement;
        new (): HTMLRfTagElement;
    };
    interface HTMLElementTagNameMap {
        "rf-empty-state": HTMLRfEmptyStateElement;
        "rf-filter-bar": HTMLRfFilterBarElement;
        "rf-modal": HTMLRfModalElement;
        "rf-rating": HTMLRfRatingElement;
        "rf-recipe-card": HTMLRfRecipeCardElement;
        "rf-search-bar": HTMLRfSearchBarElement;
        "rf-tag": HTMLRfTagElement;
    }
}
declare namespace LocalJSX {
    interface RfEmptyState {
        /**
          * @default 'Nothing here yet'
         */
        "heading"?: string;
        /**
          * @default '🍲'
         */
        "icon"?: string;
        /**
          * @default ''
         */
        "message"?: string;
    }
    interface RfFilterBar {
        /**
          * @default []
         */
        "groups"?: FilterGroup[];
        "onRfFilterChange"?: (event: RfFilterBarCustomEvent<{ group: string; value: string }>) => void;
        "onRfFilterReset"?: (event: RfFilterBarCustomEvent<void>) => void;
        /**
          * @default true
         */
        "resettable"?: boolean;
        /**
          * @default {}
         */
        "selected"?: Record<string, string>;
    }
    interface RfModal {
        /**
          * @default true
         */
        "dismissible"?: boolean;
        /**
          * @default ''
         */
        "heading"?: string;
        "onRfClose"?: (event: RfModalCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
    }
    interface RfRating {
        /**
          * @default 'Rating'
         */
        "label"?: string;
        /**
          * @default 5
         */
        "max"?: number;
        "onRfRate"?: (event: RfRatingCustomEvent<number>) => void;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default 0
         */
        "value"?: number;
    }
    interface RfRecipeCard {
        /**
          * @default ''
         */
        "badge"?: string;
        /**
          * @default false
         */
        "compact"?: boolean;
        /**
          * @default false
         */
        "favorite"?: boolean;
        "onRfFavoriteToggle"?: (event: RfRecipeCardCustomEvent<{ recipe: RecipeCardData; favorite: boolean }>) => void;
        "onRfSelect"?: (event: RfRecipeCardCustomEvent<RecipeCardData>) => void;
        "recipe"?: RecipeCardData;
    }
    interface RfSearchBar {
        /**
          * @default 350
         */
        "debounce"?: number;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        "onRfClear"?: (event: RfSearchBarCustomEvent<void>) => void;
        "onRfSearch"?: (event: RfSearchBarCustomEvent<string>) => void;
        /**
          * @default 'Search recipes'
         */
        "placeholder"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface RfTag {
        /**
          * @default ''
         */
        "label"?: string;
        "onRfRemove"?: (event: RfTagCustomEvent<string>) => void;
        /**
          * @default false
         */
        "removable"?: boolean;
        /**
          * @default 'neutral'
         */
        "tone"?: TagTone;
    }

    interface RfEmptyStateAttributes {
        "icon": string;
        "heading": string;
        "message": string;
    }
    interface RfFilterBarAttributes {
        "resettable": boolean;
    }
    interface RfModalAttributes {
        "open": boolean;
        "heading": string;
        "size": 'sm' | 'md' | 'lg';
        "dismissible": boolean;
    }
    interface RfRatingAttributes {
        "value": number;
        "max": number;
        "readonly": boolean;
        "label": string;
    }
    interface RfRecipeCardAttributes {
        "favorite": boolean;
        "badge": string;
        "compact": boolean;
    }
    interface RfSearchBarAttributes {
        "value": string;
        "placeholder": string;
        "label": string;
        "debounce": number;
        "disabled": boolean;
    }
    interface RfTagAttributes {
        "label": string;
        "tone": TagTone;
        "removable": boolean;
    }

    interface IntrinsicElements {
        "rf-empty-state": Omit<RfEmptyState, keyof RfEmptyStateAttributes> & { [K in keyof RfEmptyState & keyof RfEmptyStateAttributes]?: RfEmptyState[K] } & { [K in keyof RfEmptyState & keyof RfEmptyStateAttributes as `attr:${K}`]?: RfEmptyStateAttributes[K] } & { [K in keyof RfEmptyState & keyof RfEmptyStateAttributes as `prop:${K}`]?: RfEmptyState[K] };
        "rf-filter-bar": Omit<RfFilterBar, keyof RfFilterBarAttributes> & { [K in keyof RfFilterBar & keyof RfFilterBarAttributes]?: RfFilterBar[K] } & { [K in keyof RfFilterBar & keyof RfFilterBarAttributes as `attr:${K}`]?: RfFilterBarAttributes[K] } & { [K in keyof RfFilterBar & keyof RfFilterBarAttributes as `prop:${K}`]?: RfFilterBar[K] };
        "rf-modal": Omit<RfModal, keyof RfModalAttributes> & { [K in keyof RfModal & keyof RfModalAttributes]?: RfModal[K] } & { [K in keyof RfModal & keyof RfModalAttributes as `attr:${K}`]?: RfModalAttributes[K] } & { [K in keyof RfModal & keyof RfModalAttributes as `prop:${K}`]?: RfModal[K] };
        "rf-rating": Omit<RfRating, keyof RfRatingAttributes> & { [K in keyof RfRating & keyof RfRatingAttributes]?: RfRating[K] } & { [K in keyof RfRating & keyof RfRatingAttributes as `attr:${K}`]?: RfRatingAttributes[K] } & { [K in keyof RfRating & keyof RfRatingAttributes as `prop:${K}`]?: RfRating[K] };
        "rf-recipe-card": Omit<RfRecipeCard, keyof RfRecipeCardAttributes> & { [K in keyof RfRecipeCard & keyof RfRecipeCardAttributes]?: RfRecipeCard[K] } & { [K in keyof RfRecipeCard & keyof RfRecipeCardAttributes as `attr:${K}`]?: RfRecipeCardAttributes[K] } & { [K in keyof RfRecipeCard & keyof RfRecipeCardAttributes as `prop:${K}`]?: RfRecipeCard[K] };
        "rf-search-bar": Omit<RfSearchBar, keyof RfSearchBarAttributes> & { [K in keyof RfSearchBar & keyof RfSearchBarAttributes]?: RfSearchBar[K] } & { [K in keyof RfSearchBar & keyof RfSearchBarAttributes as `attr:${K}`]?: RfSearchBarAttributes[K] } & { [K in keyof RfSearchBar & keyof RfSearchBarAttributes as `prop:${K}`]?: RfSearchBar[K] };
        "rf-tag": Omit<RfTag, keyof RfTagAttributes> & { [K in keyof RfTag & keyof RfTagAttributes]?: RfTag[K] } & { [K in keyof RfTag & keyof RfTagAttributes as `attr:${K}`]?: RfTagAttributes[K] } & { [K in keyof RfTag & keyof RfTagAttributes as `prop:${K}`]?: RfTag[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rf-empty-state": LocalJSX.IntrinsicElements["rf-empty-state"] & JSXBase.HTMLAttributes<HTMLRfEmptyStateElement>;
            "rf-filter-bar": LocalJSX.IntrinsicElements["rf-filter-bar"] & JSXBase.HTMLAttributes<HTMLRfFilterBarElement>;
            "rf-modal": LocalJSX.IntrinsicElements["rf-modal"] & JSXBase.HTMLAttributes<HTMLRfModalElement>;
            "rf-rating": LocalJSX.IntrinsicElements["rf-rating"] & JSXBase.HTMLAttributes<HTMLRfRatingElement>;
            "rf-recipe-card": LocalJSX.IntrinsicElements["rf-recipe-card"] & JSXBase.HTMLAttributes<HTMLRfRecipeCardElement>;
            "rf-search-bar": LocalJSX.IntrinsicElements["rf-search-bar"] & JSXBase.HTMLAttributes<HTMLRfSearchBarElement>;
            "rf-tag": LocalJSX.IntrinsicElements["rf-tag"] & JSXBase.HTMLAttributes<HTMLRfTagElement>;
        }
    }
}
